### ISSUE TITLE
Ошибочный ответ от бота

### ISSUE THREAD

**Issue by mvolotov** [digitalstars/simpleVK-php#13]
Использую пример callback_example. Бот отвечает, но по нескольку раз на одно сообщение, а иногда просто начинает флудить на как ненормальный.  В неудавшихся ответах появляется куча сообщений "Incorrect response text" со следующим содержанием:

> HTTP/1.1 200 OK
> Date: Thu, 18 Jul 2019 14:01:14 GMT
> Content-Type: text/html; charset=UTF-8
> Transfer-Encoding: chunked
> Connection: keep-alive
> Server: awex
> X-Xss-Protection: 1; mode=block
> X-Content-Type-Options: nosniff
> X-Request-ID: 2801075622357e2478db77295c468308
> 
> п»їok

Версия API 5.95, как в примере.

**Comment by digitalstars** [comment]
Есть 2 предположения
1) Вероятнее всего, у файла просто слетела кодировка. Нужно перекодировать сам файл
2) Возможно это связано с довольно редким сервером awex, первый раз такой вижу. Можешь попробовать другой сервер, или делать бота через longpoll

**Comment by mvolotov** [comment]
Действительно, сервер awex, попробую сделать longpoll, посмотрю что вышло

**Comment by digitalstars** [comment]
Проблема решилась?
