### ISSUE TITLE
Получить имя пользователя

### ISSUE THREAD

**Issue by HiLevel16** [digitalstars/simpleVK-php#14]
Так и не нашел метода, который бы позволил получить имя/фамилию юзера. Как мне это сделать?

**Comment by digitalstars** [comment]
Смотря для какой цели. Если тебе нужно написать что-то вроде:
"привет, NAME", то для такой цели можно использовать placeholders(предпочтительно) или функцию getAlias()
Если нужно просто получить имя и фамилию, то для этого есть метод userInfo()
