### ISSUE TITLE
Message и user_ids

### ISSUE THREAD

**Issue by shell1986** [digitalstars/simpleVK-php#15]
Добрый день, в документации прочитал следующие

> Для отправки сообщения используйте метод messages.send. Обратите внимание, что с ключом доступа сообщества можно совершать до 20 запросов в секунду. Вы можете сократить число запросов к API, если группировать сообщения с одинаковым текстом (параметр message) для разных получателей — для этого перечислите идентификаторы получателей (до 100) в параметре user_ids. Кроме того, Вы можете группировать вызовы любых методов API, включая messages.send, с помощью execute — до 25 вызовов в одном запросе.

Скажите есть ли это свойство в вашем проекте? А если есть не скажете как оно работает? Будет создаваться беседа?

**Comment by digitalstars** [comment]
Вы про execute? Его поддержка есть, в документации это прописано, и есть пример использования на главной странице github. Беседа не создается, просто вместо N числа методов (до 25) выполняется только 1
