### ISSUE TITLE
Поддержка ссылок в клавиатуре

### ISSUE THREAD

**Issue by submgr** [digitalstars/simpleVK-php#16]
Есть ли поддержка кнопок-ссылок в клавиатуре ? Если да, то можно подробнее об этом ?

**Comment by digitalstars** [comment]
В документации не написано, т.к. эта версия библиотеки уже скоро перестанет поддерживается, но да, поддержка есть
buttonOpenLink($text, $link, $payload = null)

**Comment by submgr** [comment]
всмысли, а гди другая версия

**Comment by digitalstars** [comment]
в ветке testing, но на нее еще почти нет документации

**Comment by submgr** [comment]
`$connectionButton2 = $vk->buttonOpenLink("just test", "google.com", $payload = null);`
не хочет работать

**Comment by digitalstars** [comment]
Убери 3 параметр полностью.
