### ISSUE TITLE
получение изображений

### ISSUE THREAD

**Issue by submgr** [digitalstars/simpleVK-php#17]
если юзер прикрепил к сообщению изображение, его можно катко получить для дальнейшем работы ?

**Comment by digitalstars** [comment]
$data = $vk->initVars();
$data->object->message->attachments; (для версии выше 5.103)
Там хранятся медиавложения. Подробнее по их структуре можно посмотреть тут [https://vk.com/dev/objects/attachments_m](https://vk.com/dev/objects/attachments_m)
