### ISSUE TITLE
[Не критично, просто нужна помощь] Проблема с sendImage()

### ISSUE THREAD

**Issue by wlasser** [digitalstars/simpleVK-php#2]
```
$vk = new vk_api(VK_KEY, VERSION);
$filename = 'images/1.jpg';
$vk->sendImage($id, $filename);
```

В общем-то именно здесь и  проблема, возможно что-то не так делаю. Остальные методы вроде работают. Я могу оправлять сообщения, кнопки, но вот с отправкой изображений - все рушится с исключением: "Не удалось загрузить файл на сервер."
Работаю с ключом сообщества.

Возможно проблема с API или что-то я делаю не так?

**Comment by digitalstars** [comment]
Думаю, что проблема в том, что вы используете сервер/хостинг, на котором отключен cURL.
Для ubuntu 16 и PHP 7.0: sudo apt-get install php-curl и включить этот модуль в php.ini и сделать service apach2 restart или service nginx restart

**Comment by wlasser** [comment]
seems that is weird, im look over you sender, and that look's like courutine, but it's doesn't work, it's long-poll? I need to change method? and make that like php socket server or what?
Don't look over my english speech, that just for training, Me. And you, if you are understood me.
Спасибо за ответ.

**Comment by digitalstars** [comment]
Не совсем понял, о чем ты. Этот метод можно вызывать как longpoll так и callback. А почему он не работает - я написал выше. Некоторые хостинги не включают curl, даже если написано, что он включен. Решение - переходи на свой vds
