### ISSUE TITLE
LongPool 

### ISSUE THREAD

**Issue by HEALEXXZT** [digitalstars/simpleVK-php#23]
Здравствуйте. 
Как сделать не знаю коннект к сайту или что, чтобы LongPool всегда работал?

**Comment by digitalstars** [comment]
Longpoll нужно запускать из консоли сервера без связи с оболочкой, например через nohup. Можно конечно и через браузер, но тогда нужно в начало скрипта поставить set_time_limit(0);
Ну и будьте внимательны, запустив скрипт таким образом, его можно выключить только из консоли или перезапуском веб-сервера. Либо нужно прогать в боте команду, которая будет убивать скрипт. А еще вы можете так случайно запустить несколько копий скрипта. В общем советую юзать callback
