### ISSUE TITLE
Обработка кнопок в ф-и sendButton

### ISSUE THREAD

**Issue by sergic-chist** [digitalstars/simpleVK-php#25]
Перечень кнопок для отправки в диалог собираю по шаблону [[$btn_50], [$btn_51],[$btn_52]] в цикле (так вышло, что количество кнопок зависит от результатов в цикле) в строковую переменную или в массив(т.е. $buts='[[$btn_50], [$btn_51],[$btn_52]]' или $buts=[], где каждый элемент его это [$btn_5n]), а после передаю переменной в функцию sendButton.
Получается что-то типа $vk->sendButton($peer_id, $text, $buts, true);
но эта конструкция никак не хочет работать.
Если вместо $buts явно прописать кнопки - все работает.
Подскажите, как в sendButton запехать кнопки в переменной?
PS. Сами кнопки в цикле тоже создаются в этими же названиями ($btn_50= $vk->buttonText(...))
Спасибо!

**Comment by digitalstars** [comment]
Здравствуйте! Вот пример рабочего кода, генерации и отправки (inline) клавиатуры
```php
$vk = vk_api::create("TOKEN", "5.110");

$buttons = [];
for ($i = 0; $i < 3; ++$i) {
    for ($j = 0; $j < 3; ++$j) {
        $buttons[$i][$j] = $vk->buttonText("$i/$j", 'blue');
    }
}

$vk->sendButton(1, "Тестовая клавиатура", $buttons, true);
```

Скорее всего, у вас не работает из-за превышения лимитов на количество кнопок в ВК. Для обычной клавиатуры максимум может быть 5 x 10, и в сумме не должно быть больше 40 кнопок. Для inline клавиатуры максимальный размер 5 x 6 и в сумме не более 10 клавиш, подробнее в [офф документации](https://vk.com/dev/bots_docs_3?f=4.%2B%D0%9A%D0%BB%D0%B0%D0%B2%D0%B8%D0%B0%D1%82%D1%83%D1%80%D1%8B%2B%D0%B4%D0%BB%D1%8F%2B%D0%B1%D0%BE%D1%82%D0%BE%D0%B2)
