### ISSUE TITLE
Помогите разобраться 

### ISSUE THREAD

**Issue by SergeySviridov** [digitalstars/simpleVK-php#27]
Скачал композером , 
подключил согласно документации, 
добавил токен группы . 
Запустил в браузере LongPoll . 
Отправил сообщение в группу для теста ... 
Браузер напугал ошибкой : 

Warning: Undefined property: stdClass::$peer_id in /var/www/s185489/data/vendor/digitalstars/simplevk/src/LongPoll.php on line 186

Warning: Undefined property: stdClass::$peer_id in /var/www/s185489/data/vendor/digitalstars/simplevk/src/LongPoll.php on line 187

Fatal error: Uncaught [Exception]: возникла ошибка: [Exception]: текст: {"error":{"error_code":100,"error_msg":"One of the parameters specified was missing or invalid: you should specify peer_id, user_id, domain, chat_id or user_ids param","request_params":[{"key":"method","value":"messages.send"},{"key":"oauth","value":"1"},{"key":"peer_id","value":""},{"key":"v","value":"5.95"},{"key":"random_id","value":"1297270374"}]}} [Exception]: код ошибки: 100 [Exception]: файл: /var/www/s185489/data/vendor/digitalstars/simplevk/src/vk_api.php:229 [Exception]: путь ошибки: #0 /var/www/s185489/data/vendor/digitalstars/simplevk/src/LongPoll.php(187): DigitalStar\vk_api\vk_api->request() #1 /var/www/s185489/data/www/mft.wehobby.ru/index.php(18): DigitalStar\vk_api\LongPoll->reply() #2 /var/www/s185489/data/vendor/digitalstars/simplevk/src/LongPoll.php(85): {closure}() #3 /var/www/s185489/data/www/mft.wehobby.ru/index.php(19): DigitalStar\vk_api\LongPoll->listen() #4 {main} thrown in /var/www/s185489/data/vendor/digitalstars/simplevk/src/vk_api.php on line 229

**Comment by digitalstars** [comment]
Используйте последнюю версию vk api, или как минимум 5.103

**Comment by wlasser** [comment]
Дак разве LongPoll не через интерпретатор запускается, через командную строку?

**Comment by SergeySviridov** [comment]
С последней версией 5.130 функционирует , но заваливает эхом https://wehobby.ru/res.png . Непонятно.

**Comment by SergeySviridov** [comment]
> Дак разве LongPoll не через интерпретатор запускается, через командную строку?
Через командную , но надо ж для начала разобраться прежде чем запускать. Потому из браузера тестирую.

**Comment by SergeySviridov** [comment]
> Дак разве LongPoll не через интерпретатор запускается, через командную строку?

Через командную , но надо ж для начала разобраться прежде чем запускать. Потому из браузера тестирую.

**Comment by SergeySviridov** [comment]
> Дак разве LongPoll не через интерпретатор запускается, через командную строку?

Через командную , но надо ж для начала разобраться прежде чем запускать. Потому из браузера тестирую.

**Comment by digitalstars** [comment]
> 
> 
> С последней версией 5.130 функционирует , но заваливает эхом https://wehobby.ru/res.png . Непонятно.

У вас включены исходящие события, и происходит рекурсия
