### ISSUE TITLE
Module mbstring already loaded

### ISSUE THREAD

**Issue by MrHoller** [digitalstars/simpleVK-php#35]
Подключил бота, и он в ЛС постоянно спамит сообщением
`E_CORE_WARNING[32] Module 'mbstring' already loaded (Unknown на 0 строке)`
Даже в моменты когда им никто не пользуется. Как исправить?
SimpleVk 3 
mbstring включен в php.ini
Сервер apache2
Подключен по callback

**Comment by labi-le** [comment]
в некоторых сборках php mbstring уже идёт в пакетах, закоментируй его в своём php.ini
