### ISSUE TITLE
Composer.json + vk_api

### ISSUE THREAD

**Issue by nazbav** [digitalstars/simpleVK-php#4]
В файле композитора не указаны требования расширений: 
```json
"ext-curl": "*",
"ext-json": "*"
```
Функция initVars, класса vk_api, использует конструкции допустимые только с PHP 7.
![image](https://user-images.githubusercontent.com/21163205/56503446-81a8d980-6526-11e9-80dc-577fbdb5e8da.png)

Местами не указаны комментарии.

Отсутствует обратный слеш (или use Exception;) перед Exception, что может привести к ошибке (в случай если поиск Exception будет осуществляться в пространстве имен проекта).
![image](https://user-images.githubusercontent.com/21163205/56503787-8de16680-6527-11e9-946b-9dbfe8f8419e.png)

**Comment by digitalstars** [comment]
Исправлено
